# Generated by Django 6.0 on 2025-12-04 17:13

import django.core.validators
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Время на выполнение должно быть не более 120 секунд",
                validators=[django.core.validators.MinValueValidator(1), habits.validators.validate_duration],
                verbose_name="Время на выполнение (в секундах)",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("related_habit__isnull", False), ("reward__gt", ""), _negated=True),
                name="exclusive_reward_or_related",
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_pleasant", True), ("reward__gt", ""), _negated=True), name="pleasant_no_reward"
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_pleasant", True), ("related_habit__isnull", False), _negated=True),
                name="pleasant_no_related",
            ),
        ),
    ]
