# Generated by Django 6.0 on 2025-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_duration_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="habit",
            name="exclusive_reward_or_related",
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                default="daily",
                help_text="Как часто выполнять привычку",
                max_length=10,
                verbose_name="Периодичность",
            ),
        ),
    ]
