# Generated by Django 5.2.9 on 2025-12-12 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramConnectionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Код подтверждения"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID в Telegram (после привязки)",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Действителен до")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "django_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь Django",
                    ),
                ),
            ],
            options={
                "verbose_name": "Код привязки Telegram",
                "verbose_name_plural": "Коды привязки Telegram",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="Числовой ID пользователя в Telegram",
                        unique=True,
                        verbose_name="ID в Telegram",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Username в Telegram",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Имя в Telegram",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Фамилия в Telegram",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Бот активен для пользователя"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Код языка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "django_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь Django",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь Telegram",
                "verbose_name_plural": "Пользователи Telegram",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "morning_reminder_time",
                    models.TimeField(
                        default="09:00", verbose_name="Утреннее напоминание"
                    ),
                ),
                (
                    "evening_reminder_time",
                    models.TimeField(
                        default="21:00", verbose_name="Вечернее напоминание"
                    ),
                ),
                (
                    "enable_daily_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Ежедневные напоминания"
                    ),
                ),
                (
                    "enable_habit_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Напоминания о привычках"
                    ),
                ),
                (
                    "enable_weekly_reports",
                    models.BooleanField(
                        default=True, verbose_name="Еженедельные отчеты"
                    ),
                ),
                (
                    "enable_streak_alerts",
                    models.BooleanField(
                        default=True, verbose_name="Оповещения о сериях"
                    ),
                ),
                (
                    "remind_before_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Напоминать за (минут)"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=50,
                        verbose_name="Часовой пояс",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="telegram_bot.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="SentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("habit_reminder", "Напоминание о привычке"),
                            ("daily_summary", "Ежедневный отчет"),
                            ("weekly_report", "Еженедельный отчет"),
                            ("streak_alert", "Оповещение о серии"),
                            ("welcome", "Приветственное сообщение"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message_text", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to="telegram_bot.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленное уведомление",
                "verbose_name_plural": "Отправленные уведомления",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["sent_at", "notification_type"],
                        name="telegram_bo_sent_at_df1844_idx",
                    )
                ],
            },
        ),
    ]
