# Generated by Django 5.2.9 on 2025-12-07 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.BigIntegerField(unique=True, verbose_name="ID чата в Telegram")),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя пользователя в Telegram"),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("language_code", models.CharField(default="ru", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь Telegram",
                "verbose_name_plural": "Пользователи Telegram",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("morning_reminder_time", models.TimeField(default="09:00", verbose_name="Утреннее напоминание")),
                ("evening_reminder_time", models.TimeField(default="21:00", verbose_name="Вечернее напоминание")),
                ("enable_daily_reminders", models.BooleanField(default=True, verbose_name="Ежедневные напоминания")),
                ("enable_habit_reminders", models.BooleanField(default=True, verbose_name="Напоминания о привычках")),
                ("enable_weekly_reports", models.BooleanField(default=True, verbose_name="Еженедельные отчеты")),
                ("enable_streak_alerts", models.BooleanField(default=True, verbose_name="Оповещения о сериях")),
                (
                    "remind_before_minutes",
                    models.PositiveIntegerField(default=15, verbose_name="Напоминать за (минут)"),
                ),
                ("timezone", models.CharField(default="Europe/Moscow", max_length=50, verbose_name="Часовой пояс")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="telegram_bot.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="SentNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("habit_reminder", "Напоминание о привычке"),
                            ("daily_summary", "Ежедневный отчет"),
                            ("weekly_report", "Еженедельный отчет"),
                            ("streak_alert", "Оповещение о серии"),
                            ("welcome", "Приветственное сообщение"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message_text", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_delivered", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "habit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="habits.habit"
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to="telegram_bot.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленное уведомление",
                "verbose_name_plural": "Отправленные уведомления",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["sent_at", "notification_type"], name="telegram_bo_sent_at_df1844_idx")
                ],
            },
        ),
    ]
